services:
  app:
    image: ghcr.io/amalia-gorgan/fintrack:latest
    container_name: fintrack_app
    depends_on:
      mssql:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=${DB_NAME:-fintrackdb};encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ${MSSQL_SA_PASSWORD}
      SERVER_PORT: 8000
    ports:
      - "8000:8000"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fintrack_mssql
    restart: unless-stopped
    env_file: .env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "${HOST_DB_PORT:-1433}:1433"
    healthcheck:
      # NOTE: -C is the important part: "trust server certificate"
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
